# Changing this file necessitates a server restart
name: "Journal of Publishing it Yourself"
abbreviation: "JOPIY"
issn: ""
tagline: "a test journal."
logo_url: "https://joss.theoj.org/logo_large.jpg"
url: "https://odcambc.com"
editor_email: ""
noreply_email: ""
launch_date: "2024-05-05"
twitter: ""
mastodon_url: ""
google_analytics: "-4"
github: ""
reviews: ""
papers_repo: ""
papers_html_url: ""
reviewers_url: ""
reviewers_signup_url: ""
reviewers_lookup_url: ""
product: "software" # the *thing* being submitted for review
submission_enquiry: |-
  **Project repository URL:** INSERT YOUR REPOSITORY LINK HERE

  Briefly describe your software, its research application and any questions you have about the JOSS submission criteria.
paper_types: []
bot_username: editorialbot
features:
  tracks: true
